#!/usr/bin/env bash
set -euo pipefail

WITH_CROSS_TOOLCHAIN=0

for arg in "$@"; do
    case "$arg" in
        --with-cross-toolchain)
            WITH_CROSS_TOOLCHAIN=1
            ;;
        *)
            echo "Unknown argument: $arg"
            echo "Usage: $0 [--with-cross-toolchain]"
            exit 1
            ;;
    esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PACKAGES=(
    bash
    binutils
    bison
    build-essential
    ca-certificates
    curl
    flex
    g++
    gcc
    git
    grub-common
    grub2-common
    grub-pc-bin
    libgmp3-dev
    libisl-dev
    libmpc-dev
    libmpfr-dev
    make
    mtools
    qemu-system-x86
    texinfo
    xorriso
)

echo "[wsl-bootstrap] repo: $REPO_ROOT"
echo "[wsl-bootstrap] installing apt packages"
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${PACKAGES[@]}"

if [[ "$WITH_CROSS_TOOLCHAIN" -eq 1 ]]; then
    echo "[wsl-bootstrap] building x86_64-elf toolchain"
    (cd "$REPO_ROOT" && bash scripts/toolchain/build-toolchain.sh)

    PROFILE_LINE='export PATH="$HOME/.local/cross/x86_64-elf/bin:$PATH"'
    if ! grep -Fqx "$PROFILE_LINE" "$HOME/.profile"; then
        echo "$PROFILE_LINE" >> "$HOME/.profile"
        echo "[wsl-bootstrap] added cross toolchain PATH to ~/.profile"
    fi
fi

if [[ "$WITH_CROSS_TOOLCHAIN" -eq 1 ]]; then
    TARGET_VALUE="x86_64-elf"
else
    TARGET_VALUE="x86_64-linux-gnu"
fi

cat > "$REPO_ROOT/config.mk" <<EOF
# Generated by scripts/dev/wsl-bootstrap.sh
TARGET := $TARGET_VALUE
QEMU_SYSTEM := qemu-system-x86_64
EOF

echo "[wsl-bootstrap] wrote config.mk (TARGET=$TARGET_VALUE)"
echo "[wsl-bootstrap] done"
